### ISSUE TITLE
questions: rate limiting / renovate / dependabot

### ISSUE THREAD

**Issue by erzz** [aquasecurity/setup-trivy#4]
Sorry for not opening a discussion as they are not enabled for this project :)

I love that you have created this as it allows us much greater control over which version of the binary is in use than when using trivy-action!

Some initial questions:

1. Given the recent rate limiting issues with the DB - I wonder if similar rate limiting issues will exist for the fetching of the binary from the releases?   I barely understand Githubs rate limits anymore so I don't know if it would be helpful to also expose the github token as an input/secret so users could provide a PAT?

2. One thing we would lose is automated updating of trivy via renovate or dependabot. I wonder if its worth this action following the versioning of the trivy binary?  This would mean that at least the consumer would have a PR indicating that latest is new and a controlled introduction to their pipelines.    I know its unconventional - but I would argue that semantic versioning of the trivy binary is not conventional either (there is often breaking changes introduced via minor version bumps)

3. Related to 2. - perhaps latest should not be an option :)

**Comment by knqyf263** [comment]
>Given the recent rate limiting issues with the DB - I wonder if similar rate limiting issues will exist for the fetching of the binary from the releases?

Here is the document. GHCR differs from GitHub API, but rate limits on API are well described here.
https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28

>but I would argue that semantic versioning of the trivy binary is not conventional either (there is often breaking changes introduced via minor version bumps)

Trivy is yet to reach v1.0.0. You can reference https://0ver.org/.

**Comment by erzz** [comment]
Yup, no worries... I reflect at least 2 stupid things I said and thanks for opening discussions!
